name: Python Linting

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
      - name: Lint with flake8
        run: |
          flake8 src --show-source --statistics
      - name: Lint with Pylint
        run: |
          pylint src --disable=C0114,C0115,C0116
